import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Session} from '@supabase/supabase-js';
import {Network} from 'lucide-react';
import Home from './page';
import {configurationError,supabase} from './lib/backend';
import './globals.css';import './network.css';import './auth.css';
function App(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[member,setMember]=useState<{display_name:string}|null>(null),[accessError,setAccessError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[recovery,setRecovery]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data,error})=>{setSession(data.session);setReady(true);if(error)setError(error.message)});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);setReady(true);if(event==='PASSWORD_RECOVERY')setRecovery(true);if(!s){setMember(null);setAccessError('')}});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{let live=true;setMember(null);setAccessError('');if(session&&supabase)supabase.from('rede_members').select('display_name,active').eq('user_id',session.user.id).maybeSingle().then(({data,error})=>{if(!live)return;if(error)setAccessError('Não foi possível verificar seu acesso. Confira sua conexão ou a configuração do banco.');else if(!data?.active)setAccessError('Sua conta ainda não tem acesso à equipe. Peça ao responsável para habilitá-la no Supabase.');else setMember(data)});return()=>{live=false}},[session?.user.id,retry]);
 async function signOut(){if(!supabase)return;setError('');const {error}=await supabase.auth.signOut({scope:'local'});if(error)setError('Não foi possível sair. Tente novamente.');else{setMember(null);setSession(null);setPassword('');setRecovery(false)}}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(recovery){const {error}=await supabase!.auth.updateUser({password});if(error)throw error;setRecovery(false);setPassword('');setMessage('Senha atualizada.')}else{const {error}=await supabase!.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('')}}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setBusy(false)}}
 async function reset(){if(!email.trim()){setError('Informe seu e-mail para recuperar a senha.');return}setBusy(true);setError('');const {error}=await supabase!.auth.resetPasswordForEmail(email.trim(),{redirectTo:window.location.origin+window.location.pathname});setBusy(false);if(error)setError(error.message);else setMessage('Se a conta estiver cadastrada, você receberá um link para redefinir a senha.')}
 if(session&&member&&!recovery)return <Home key={session.user.id} userName={member.display_name} onSignOut={signOut}/>;
 return <main className="authscreen"><section className="authcard"><span className="logo"><Network size={24}/></span><h1>Mapeamento de rede</h1>{configurationError?<p className="error">{configurationError}</p>:!ready?<p>Verificando acesso…</p>:session&&!recovery?<><p>{accessError||'Verificando acesso à equipe…'}</p>{accessError&&<button className="button" onClick={()=>setRetry(x=>x+1)}>Verificar novamente</button>}<button className="button" onClick={signOut}>Sair</button></>:<><p>{recovery?'Defina sua nova senha.':'Entre com a conta cadastrada para sua equipe.'}</p><form onSubmit={login}>{!recovery&&<label>E-mail<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>{recovery?'Nova senha':'Senha'}<input type="password" required minLength={recovery?12:undefined} autoComplete={recovery?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<button className="button primary" disabled={busy}>{busy?'Aguarde…':recovery?'Salvar nova senha':'Entrar'}</button></form>{!recovery&&<button className="textbutton" disabled={busy} onClick={reset}>Esqueci minha senha</button>}</>}</section></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
