"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import {loadNetwork,updateRecord} from './lib/backend';
import {Network,Search,RefreshCw,History,Layers,Rows3,Pencil,Info,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Rec={id:string;kind:string;group_name:string;source:string;fields:Record<string,string|number|null>;version:number};
type Hist={id:string;record_id:string;actor:string;reason:string;before:string;after:string;created_at:string};
const labels:Record<string,string>={'Infor':'Pontos e identificação','Switchs':'Switches','PatchPannel':'Patch panels','Observações':'Observações','history':'Histórico'};
const show=(v:unknown)=>v===null||v===undefined||v===''?'—':String(v);
function Picker({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{label}</SelectItem>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function Home({userName,onSignOut}:{userName:string;onSignOut:()=>Promise<void>}){
 const request=useRef<{key:string;id:string}|null>(null);
 const [records,setRecords]=useState<Rec[]>([]),[history,setHistory]=useState<Hist[]>([]),[tab,setTab]=useState('Infor'),[query,setQuery]=useState(''),[group,setGroup]=useState('all'),[room,setRoom]=useState('all'),[usage,setUsage]=useState('all'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState<Rec|null>(null),[fields,setFields]=useState<Rec['fields']>({}),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);try{const d=await loadNetwork();setRecords(d.records);setHistory(d.history);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.');}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh();const id=setInterval(refresh,30000);return()=>clearInterval(id)},[refresh]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'search_network',description:'Busca registros e mostra a consulta na aba informada.',inputSchema:{type:'object',properties:{query:{type:'string'},source:{type:'string',enum:['Infor','Switchs','PatchPannel','Observações']}},required:['query','source'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(x:any)=>{if(typeof x.query!=='string'||!['Infor','Switchs','PatchPannel','Observações'].includes(x.source))throw Error('Consulta inválida');setTab(x.source);setQuery(x.query);setGroup('all');setRoom('all');setUsage('all');return records.filter(r=>r.kind===x.source&&JSON.stringify(r.fields).toLowerCase().includes(x.query.toLowerCase())).map(r=>({id:r.id,source:r.kind+'!'+r.source,fields:r.fields}));}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[records]);
 function open(r:Rec){request.current=null;setSelected(r);setFields({...r.fields});setReason('');setSaveError('');}
 async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;setSaving(true);setSaveError('');try{const key=JSON.stringify({id:selected.id,version:selected.version,fields,reason});if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};await updateRecord({id:selected.id,version:selected.version,fields,reason,requestId:request.current.id});setSelected(null);setNotice('Alteração salva e registrada no histórico.');await refresh()}catch(e){setSaveError(e instanceof Error?e.message:'Falha ao salvar.')}finally{setSaving(false)}}
 const subset=records.filter(r=>r.kind===tab),groups=[...new Set(subset.map(r=>r.group_name))],rooms=[...new Set(subset.map(r=>String(r.fields.SALA??'')).filter(Boolean))].sort();
 const filtered=subset.filter(r=>(group==='all'||r.group_name===group)&&(room==='all'||r.fields.SALA===room)&&(usage==='all'||r.fields.UTILIZADO===usage)&&[r.group_name,r.source,...Object.values(r.fields)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const cols=tab==='Infor'?['SW - PORT','PATCH PANEL','TIPO','SALA','STATUS','UTILIZADO']:tab==='Observações'?['OBSERVAÇÃO']:['PORTA','IDENTIFICAÇÃO','MODELO'],infos=records.filter(r=>r.kind==='Infor');
 const counts=[['Switches','5'],['Portas de switch','120'],['Patch panels','11'],['Registros em uso',String(infos.filter(r=>r.fields.UTILIZADO==='SIM').length)]];
 const visibleHistory=history.filter(h=>[h.actor,h.reason,h.record_id,h.before,h.after].join(' ').toLowerCase().includes(query.toLowerCase()));
 function exportData(){const blob=new Blob([JSON.stringify({exportadoEm:new Date().toISOString(),registros:records,historico:history},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='mapa-rede-backup.json';a.click();URL.revokeObjectURL(u)}
 return <><header className="topbar"><div className="brand"><span className="logo"><Network size={22}/></span><span>Mapa de Rede<small>OPERAÇÃO · DOCUMENTAÇÃO</small></span></div><div className="topactions"><span className="account"><span>{userName}</span><button className="button" onClick={onSignOut}>Sair</button></span><button onClick={exportData} disabled={!records.length} className="button"><Download size={16}/>Exportar</button></div></header><main className="workspace"><div className="titleline"><div><p className="eyebrow">INFRAESTRUTURA / REDE LOCAL</p><h1>Mapeamento de rede</h1><p className="subtitle">Consulte as conexões e registre cada mudança da equipe.</p></div><button className="button" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spinning':''}/>Atualizar</button></div>
 <div className="stats">{counts.map(([a,b],i)=><div key={a}><span>{a}</span><strong>{loading&&!records.length?'—':b}</strong><small>{i===3?'UTILIZADO = SIM · aba Infor':'conforme a planilha de origem'}</small></div>)}</div>
 {notice&&<div className="success" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso">×</button></div>}{error&&<div className="error" role="alert">{error} <button onClick={refresh}>Tentar novamente</button></div>}
 <section className="surface"><Tabs value={tab} onValueChange={v=>{setTab(v);setGroup('all');setRoom('all');setUsage('all')}}><TabsList className="tablist">{Object.entries(labels).map(([k,v])=><TabsTrigger key={k} value={k}>{k==='history'?<History/>:k==='Infor'?<Rows3/>:<Layers/>}{v}{k==='history'&&<span className="count">{history.length}</span>}</TabsTrigger>)}</TabsList></Tabs>
 <div className="filters"><label className="search"><Search size={18}/><input aria-label="Buscar no mapeamento" placeholder={tab==='history'?'Buscar pessoa, motivo ou ponto…':'Buscar ponto, porta, identificação…'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{tab!=='history'&&<Picker label="Todos os grupos" values={groups} value={group} onChange={setGroup}/ >}{tab==='Infor'&&<><Picker label="Todas as salas" values={rooms} value={room} onChange={setRoom}/><Picker label="Qualquer uso" values={['SIM','NÃO']} value={usage} onChange={setUsage}/></>}{(query||group!=='all'||room!=='all'||usage!=='all')&&<button className="textbutton" onClick={()=>{setQuery('');setGroup('all');setRoom('all');setUsage('all')}}>Limpar</button>}</div>
 <div className="sectionline"><span>{labels[tab]} <b>{tab==='history'?visibleHistory.length:filtered.length}</b></span><small>{tab==='history'?'Data e hora de Fortaleza':'— indica campo vazio na planilha'}</small></div>
 {loading&&!records.length?<div className="empty">Carregando o mapeamento…</div>:tab==='history'?<div className="timeline">{visibleHistory.length===0?<div className="empty"><History size={30}/><h2>Nenhuma alteração registrada</h2><p>Ao editar um registro, o responsável, o motivo e os valores anteriores ficam salvos aqui.</p></div>:visibleHistory.map(h=>{const r=records.find(x=>x.id===h.record_id);const a=JSON.parse(h.before),b=JSON.parse(h.after);return <article key={h.id}><div className="historytop"><strong>{h.actor}</strong><time>{new Date(h.created_at).toLocaleString('pt-BR',{timeZone:'America/Fortaleza'})}</time></div><p>{h.reason}</p><small>{r?.kind} · {r?.group_name} · {r?.source} · {(h as any).origin==='migrado'?'registro importado do sistema anterior':'conta autenticada'}</small><div className="diffs">{Object.keys(b).filter(k=>a[k]!==b[k]).map(k=><div key={k}><strong>{k}</strong><del>{show(a[k])}</del><span>→</span><ins>{show(b[k])}</ins></div>)}</div></article>})}</div>:filtered.length===0?<div className="empty"><Search size={30}/><h2>Nenhum registro encontrado</h2><p>Tente outro ponto ou remova os filtros.</p></div>:tab==='Switchs'||tab==='PatchPannel'?<div className="maps">{groups.filter(g=>filtered.some(r=>r.group_name===g)).map(g=><article className="portgroup" key={g}><div className="portheading"><h2>{g}</h2><span>{tab==='Switchs'?show(filtered.find(r=>r.group_name===g)?.fields.MODELO):'Patch panel'} · {filtered.filter(r=>r.group_name===g).length} portas</span></div><div className="ports">{filtered.filter(r=>r.group_name===g).sort((a,b)=>Number(a.fields.PORTA)-Number(b.fields.PORTA)).map(r=><button key={r.id} onClick={()=>open(r)} className={'port '+(r.fields.IDENTIFICAÇÃO?'mapped':'blank')+(String(r.fields.IDENTIFICAÇÃO).includes('PF24')?' known':'')}><span>PORTA {String(r.fields.PORTA).padStart(2,'0')}</span><strong>{show(r.fields.IDENTIFICAÇÃO)}</strong><small>{r.source}<Pencil size={12}/></small></button>)}</div></article>)}</div>:<Table><TableHeader><TableRow><TableHead>GRUPO</TableHead>{cols.map(c=><TableHead key={c}>{c}</TableHead>)}<TableHead>ORIGEM</TableHead><TableHead><span className="sr-only">Editar</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell><span className="groupbadge">{r.group_name}</span></TableCell>{cols.map(c=><TableCell key={c} className={c==='OBSERVAÇÃO'?'observation':c==='SW - PORT'||c==='PATCH PANEL'?'mono':''}>{c==='STATUS'&&r.fields[c]?<span className={'status '+(r.fields[c]==='FUNCIONANDO'?'ok':'other')}>{show(r.fields[c])}</span>:c==='UTILIZADO'?<span className={r.fields[c]==='SIM'?'used':'muted'}>{show(r.fields[c])}</span>:show(r.fields[c])}</TableCell>)}<TableCell className="source">{r.kind}!{r.source}</TableCell><TableCell><button className="edit" onClick={()=>open(r)} aria-label={'Editar '+(r.fields['SW - PORT']??r.source)}><Pencil size={15}/><span>Editar</span></button></TableCell></TableRow>)}</TableBody></Table>}
 </section><footer>Fonte: MAPEAMENTO REDE (1)(1).xlsx · Switchs, Infor e PatchPannel<span>Atualização automática a cada 30 segundos</span></footer></main>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!saving)setSelected(null)}}><DialogContent className="editdialog"><DialogTitle>Editar {show(selected?.fields['SW - PORT']??selected?.group_name)}</DialogTitle><DialogDescription>{selected?.kind}!{selected?.source} · A alteração afeta somente este registro. Confira as outras abas se a mudança envolver a mesma conexão.</DialogDescription><form onSubmit={save}><div className="formfields">{(selected?.kind==='Infor'?['SW - PORT','PATCH PANEL','TIPO','SALA','STATUS','UTILIZADO']:selected?.kind==='Observações'?['OBSERVAÇÃO']:['PORTA','IDENTIFICAÇÃO',...(selected?.kind==='Switchs'?['MODELO']:[])]).map(k=>{const v=fields[k];return <label key={k}>{k}<input value={v??''} maxLength={2000} onChange={e=>setFields(f=>({...f,[k]:e.target.value===''?null:typeof selected?.fields[k]==='number'?Number(e.target.value):e.target.value}))} type={typeof selected?.fields[k]==='number'?'number':'text'}/></label>})}</div><div className="auditfields"><label>Responsável<input value={userName} readOnly className="readonly"/></label><label>Motivo da alteração <span>*</span><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: ponto remanejado após troca de mesa"/></label></div><p className="hint">O histórico guarda data, conta autenticada e valores antes/depois.</p>{saveError&&<p className="error" role="alert">{saveError}</p>}<div className="formactions"><button type="button" className="button" disabled={saving} onClick={()=>setSelected(null)}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando…':'Salvar e registrar'}</button></div></form></DialogContent></Dialog>
 </>;
}
